apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contacts-ingress
  labels:
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.host }}
    - http:
        paths:
          - pathType: {{ .Values.ingress.pathType }}
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: contactsservice
                port:
                  number: {{ .Values.deployment.appPort }}