apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contacts-ingress
  labels:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "{{ .Values.issuer.issuerName }}"
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: {{ .Values.ingress.pathType }}
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: contactsservice
                port:
                  number: {{ .Values.deployment.appPort }}