apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
type: Opaque
data:
  MONGO_DBNAME: {{ .Values.secret.dbname }}
  MONGODB_USERNAME: {{ .Values.secret.user }}
  MONGODB_PASSWORD: {{ .Values.secret.password }}
  MONGODB_HOSTNAME: {{ .Values.secret.host }}
  MONGODB_URL_SUFFIX: {{ .Values.secret.suffix }}
  SECRET_KEY: {{ .Values.secret.secretkey }}