---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: contactsapp
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: contactsapp
  chart:
    git: git@github.com:ToviKolitz/contactappConfig.git
    path: charts/contacts
    ref: master
  values:
    image:
      repository: 006262944085.dkr.ecr.us-east-2.amazonaws.com/contactapp
      tag: 1.0.39
